### ISSUE TITLE
econf_mergeFiles and delimiter/comments

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/libeconf#106]
/etc/default/su uses '#' as comment and "=" as seperator, /etc/login.defs uses " \t" as delimiter.

Should econf_mergeFiles merge comments and delimiter, or which of the two should be used?

**Comment by laenion** [comment]
Currently the delimiter and comment char of the first file will always win.

**Comment by schubi2** [comment]
> Currently the delimiter and comment char of the first file will always win.

I have updated the docu in order to make this more clearl.

**Comment by schubi2** [comment]
I think it makes not sense to mix delimiters, commends in ONE file. But I have added functions to set these values in an econf_file object. So the user has the freedom to change it before writing the data to file.
