### ISSUE TITLE
Security: allow enforcing config file/dir ownership and permissions

### ISSUE THREAD

**Issue by mwilck** [openSUSE/libeconf#113]
Configuration files can be security sensitive in various ways. They may contain options to specify  programs to run, specify network ports to open, allow certain actions for certain users or groups or public keys, or other stuff I haven't yet thought about. Sometimes they may even contain sensitive stuff like passwords. Therefore, a program may want to make sure that all configuration it reads is taken from files or directories with appropriate permissions (e.g. writeable only to root, readable only for members of a certain group), and refuse reading config files via symlinks (to avoid symlink attacks). It depends on the application which permissions are allowable.

With libeconf, the paths of the configuration files are opaque to the calling program. Actually the program may not be aware of all files that libeconf parses. Thus libeconf needs an API for the program to call to ensure all configuration files have permissions that are appropriate for the application's use case, something like this:

     econf_requireAuth(uid_t owner, gid_t group, 
               mode_t file_perms, mode_t dir_perms, bool allow_symlinks);

This function would need to be called before calling libeconf functions that parse configuration. It would instruct libeconf to refuse to parse content of configuration files that don't  comply with the application's requirements. `dir_perms` and `file_perms` would be bit masks such that directories or files, respectively, which have permission bits set that are not set in these masks, would not be opened. Not sure if `allow_symlinks` makes sense; perhaps libeconf should generally refuse reading symlinks. Alternatively, there could also be a set of functions:

    econf_requireOwner(uid_t owner);
    econf_requireGroup(gid_t group);
    econf_requirePermissions(mode_t file_perms, mode_t dir_perms);
    econf_followSymlinks(bool allow);

That would have the advantage to make it easier to impose restrictions only on some properties (e.g. enforce permissions but not owner).

**Comment by schubi2** [comment]
Implemented with https://github.com/openSUSE/libeconf/pull/165
Will be in the next release. Thank you for your explanations !
