### ISSUE TITLE
Allow using of @PARENT_TAG@ on OBS builds

### ISSUE THREAD

**Issue by PerryWerneck** [openSUSE/libeconf#131]
This is not exactly an issue, is more like a suggestion:

It would be easy for packagers if you use tags without the "v" on version number allowing a more standard version on packages built with OBS using the @PARENT_TAG@ to auto-set the version.

**Comment by Vogtinator** [comment]
Using `v` as prefix for tags is used pretty often. To strip that from the tag name in OBS services, you can use the `versionrewrite` option: https://github.com/openSUSE/obs-service-tar_scm/blob/aed496967888b69c771a8c0838c2d7c37fef315f/tar_scm.service.in#L101

**Comment by schubi2** [comment]
I must admit that I do not understand the request at all. Sorry...
Could you please give an example ?

**Comment by laenion** [comment]
I think it's about release tag, and you (obviously accidentally) released the latest version without the leading `v` already: https://github.com/openSUSE/libeconf/tags. You could declare that a feature now to close this bug :-)

In general I'd also prefer simple version tags, but the `v` syntax seems to have won for most projects I'm aware of.

**Comment by PerryWerneck** [comment]
> I must admit that I do not understand the request at all. Sorry...
> Could you please give an example ?

Just tested here (https://build.opensuse.org/package/show/home:PerryWerneck/libeconf) and it works! Tks.

**Comment by PerryWerneck** [comment]
> Using `v` as prefix for tags is used pretty often. To strip that from the tag name in OBS services, you can use the `versionrewrite` option: https://github.com/openSUSE/obs-service-tar_scm/blob/aed496967888b69c771a8c0838c2d7c37fef315f/tar_scm.service.in#L101

Just tested here (https://build.opensuse.org/package/show/home:PerryWerneck/libeconf) and it works! Tks!

**Comment by Vogtinator** [comment]
> > Using `v` as prefix for tags is used pretty often. To strip that from the tag name in OBS services, you can use the `versionrewrite` option: https://github.com/openSUSE/obs-service-tar_scm/blob/aed496967888b69c771a8c0838c2d7c37fef315f/tar_scm.service.in#L101
> 
> Just tested here (https://build.opensuse.org/package/show/home:PerryWerneck/libeconf) and it works! Tks!

Note that you should not use quotes there, XML doesn't require that. While that appears to work now, it might not in the future.
