### ISSUE TITLE
Covscan FORWARD_NULL issues

### ISSUE THREAD

**Issue by ikerexxe** [openSUSE/libeconf#149]
Even though I wanted to fix these issues I'm having a hard time understanding them. For me it doesn't have any sense to compare a variable to NULL and then using its value. So, I'm opening this ticket in case somebody with a better understanding of the code can fix them.

Error: FORWARD_NULL (CWE-476): [#def8]
libeconf-0.3.8/lib/libeconf.c:91: var_compare_op: Comparing "comment" to null implies that "comment" might be null.
libeconf-0.3.8/lib/libeconf.c:96: var_deref_model: Passing null pointer "comment" to "read_file", which dereferences it.
   94|       (*key_file)->comment = '#';
   95|   
   96|->   t_err = read_file(*key_file, absolute_path, delim, comment);
   97|     free (absolute_path);
   98|   

Error: FORWARD_NULL (CWE-476): [#def9]
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "etc_file->file_entry" to null implies that "etc_file->file_entry" might be null.
libeconf-0.3.8/lib/libeconf.c:135: var_deref_model: Passing "etc_file" to "insert_nogroup", which dereferences null "etc_file->file_entry".
  133|         (usr_file->file_entry == NULL ||
  134|          strcmp(usr_file->file_entry->group, KEY_FILE_NULL_VALUE))) {
  135|->     merge_length = insert_nogroup(&fe, etc_file);
  136|     }
  137|     merge_length = merge_existing_groups(&fe, usr_file, etc_file, merge_length);

Error: FORWARD_NULL (CWE-476): [#def10]
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "etc_file->file_entry" to null implies that "etc_file->file_entry" might be null.
libeconf-0.3.8/lib/libeconf.c:137: var_deref_model: Passing "etc_file" to "merge_existing_groups", which dereferences null "etc_file->file_entry".
  135|       merge_length = insert_nogroup(&fe, etc_file);
  136|     }
  137|->   merge_length = merge_existing_groups(&fe, usr_file, etc_file, merge_length);
  138|     merge_length = add_new_groups(&fe, usr_file, etc_file, merge_length);
  139|     (*merged_file)->length = merge_length;

Error: FORWARD_NULL (CWE-476): [#def11]
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "usr_file->file_entry" to null implies that "usr_file->file_entry" might be null.
libeconf-0.3.8/lib/libeconf.c:137: var_deref_model: Passing "usr_file" to "merge_existing_groups", which dereferences null "usr_file->file_entry".
  135|       merge_length = insert_nogroup(&fe, etc_file);
  136|     }
  137|->   merge_length = merge_existing_groups(&fe, usr_file, etc_file, merge_length);
  138|     merge_length = add_new_groups(&fe, usr_file, etc_file, merge_length);
  139|     (*merged_file)->length = merge_length;

Error: FORWARD_NULL (CWE-476): [#def12]
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "usr_file->file_entry" to null implies that "usr_file->file_entry" might be null.
libeconf-0.3.8/lib/libeconf.c:138: var_deref_model: Passing "usr_file" to "add_new_groups", which dereferences null "usr_file->file_entry".
  136|     }
  137|     merge_length = merge_existing_groups(&fe, usr_file, etc_file, merge_length);
  138|->   merge_length = add_new_groups(&fe, usr_file, etc_file, merge_length);
  139|     (*merged_file)->length = merge_length;
  140|     (*merged_file)->alloc_length = merge_length;

**Comment by schubi2** [comment]
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "usr_file->file_entry" to null implies that "usr_file->file_entry" might be null.
libeconf-0.3.8/lib/libeconf.c:131: var_compare_op: Comparing "etc_file->file_entry" to null implies that "etc_file->file_entry" might be null.

Hm, I believe that it is wrong. I have failing test cases if I am removing this check which is from my point of view needed.

The rest are valid points which I have fixed:
https://github.com/openSUSE/libeconf/pull/150

Thanks for your hints !!!

**Comment by ikerexxe** [comment]
Thanks to you for taking them into account.
