### ISSUE TITLE
0.4.1: doxygen generates messy lvl3 man pages and is used unconditionally only if found

### ISSUE THREAD

**Issue by kloczek** [openSUSE/libeconf#154]
```console
total 48
-rw-r--r-- 1 tkloczko tkloczko  1549 Jul  9 14:17 econf_ext_value.3
-rw-r--r-- 1 tkloczko tkloczko   377 Jul  9 14:17 _home_tkloczko_rpmbuild_BUILD_libeconf-0.4.1_include_.3
-rw-r--r-- 1 tkloczko tkloczko  2057 Jul  9 14:17 libeconf_ext.h.3
-rw-r--r-- 1 tkloczko tkloczko 31981 Jul  9 14:17 libeconf.h.3
-rw-r--r-- 1 tkloczko tkloczko   219 Jul  9 14:17 README.md.3
```
Hoever those man pages are mnot installed and `install` target installs doc/man/libeconf.3.

It is not possible as well diisable use doxygen. If doxygen has been found it is automatically used.

**Comment by schubi2** [comment]
Well, these files are generated by docygen in the build directory. I do not see a real issue here. Yes, not nice, but....
>It is not possible as well diisable use doxygen. If doxygen has been found it is automatically used.
Maybe that's a point for you. Do you have any suggestions how and where to set this. PRs are very welcome :-)

**Comment by schubi2** [comment]
I have had a look on it again. We need these files in order to copy and past the content of these file to doc/man/libeconf.3.
So, they are not so useless. :-)

**Comment by kloczek** [comment]
I cannot find in last commits fix for that issue.
