### ISSUE TITLE
econftool reports parse error with login.defs

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/libeconf#162]
With current openSUSE Tumbleweed:

```
node178:~ # econftool show login.defs
10: Missing delimiter
```
1. as we read several files, we should print in which file line "10" is broken.
2. Line 1-8 are comments, line 9 is an empty line, line 10 only contains the "#" character. I cannot find a syntax error or missing delimiter

Looks like something is broken here with reading login.defs.

**Comment by schubi2** [comment]
I have improved the error report and have fixed the parsing:
./econftool show --delimiters="=" /tmp/login.defs
/tmp/login.defs (line 15): Missing delimiter
