### ISSUE TITLE
Parse system-wide drop-in files also when admin config file in /etc is present

### ISSUE THREAD

**Issue by laenion** [openSUSE/libeconf#174]
Drop-in files (e.g. in _/usr/etc/application.conf.d/extension.conf_) are a common way to change the default configuration of an application when installing an auxiliary package such as a plugin or a customization package to adopt the application for a certain environment.

The current behavior however prevents using this mechanism: As soon as an admin configuration file is present in _/etc/application.conf_, the drop-ins in _/usr/etc/application.conf.d_ won't be read any more. This will lead to the problem that packages basically cannot install any configuration drop-ins, as they would have to be installed into _/etc/application.conf.d_, but _/etc_ is reserved for admin changes.

One option would be to educate the admin that he simply should never copy the complete configuration file (in this case _/etc/application.conf_), however this doesn't seem practical.
I'd urge to change the behavior to the one of systemd described in https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description instead:
> In addition to /etc/systemd/system, the drop-in ".d/" directories for system services can be placed in /usr/lib/systemd/system or /run/systemd/system directories. Drop-in files in /etc/ take precedence over those in /run/ which in turn take precedence over those in /usr/lib/. Drop-in files under any of these directories take precedence over unit files wherever located. Multiple drop-in files with different names are applied in lexicographic order, regardless of which of the directories they reside in.

Or in other words: drop-in files will always be read from all directories; if one wants to overwrite one of them, one will have to do so by creating a file of the same name in _/etc_.

**Comment by schubi2** [comment]
Hm, not sure. For me the descriptions says only that drop in files in /usr und /run has less prio than drop in files in /etc.
Or I am wrong ?

**Comment by thkukuk** [comment]
/etc/application.conf overwrites **ALL** files in /usr/etc, including /usr/etc/application.conf.d!
That's why the admin should create drop ins in /etc/application.conf.d/* and not create an /etc/application.conf file.
Look at systemd documentation or try it yourself with systemd.

**Comment by thkukuk** [comment]
They really changed it :(
```
    Loaded: loaded (/etc/systemd/system/testunit.service; static)
    Drop-In: /usr/lib/systemd/system/testunit.service.d
             └─on.conf
```

**Comment by schubi2** [comment]
The question would be, if we are following them ? I am not really a fan of it.

**Comment by laenion** [comment]
I can't remember a time when the behavior in systemd was different, and even the Changelog entry for version 198 (where drop-ins were introduced) in https://github.com/systemd/systemd/blob/main/NEWS also suggests it has always been that way.

**Comment by admd** [comment]
Do we have any update for this issue?

**Comment by schubi2** [comment]
> Do we have any update for this issue?
Yes, we have decided to do the same way like systemd is doing it. I am on the way.... :-)

**Comment by schubi2** [comment]
Version 0.5.1

Reading files in /usr/vendor/example.suffix.d/* regardless
there is a /etc/example.suffix file.

**Comment by schubi2** [comment]
I hope, it is working :-)
