### ISSUE TITLE
Behavior of econf_getKeys() when providing no group

### ISSUE THREAD

**Issue by tiltingpenguin** [openSUSE/libeconf#187]
The libeconf documentation claims that if you pass NULL instead of a group to the getKeys function it should return all keys in a config file (https://opensuse.github.io/libeconf/libeconf_8h.html#afa58b02e97241c5e8d778f40b04731b7) but from my testing it seems that only keys that do not have a group are returned. 

What is the intended behavior in this case?

**Comment by thkukuk** [comment]
== NULL -> all keys which do not have a group

If keys have groups and two groups have a key with identical name, returning all keys wouldn't make sense. You would have a key twice and nobody knows which of the two it is.

**Comment by tiltingpenguin** [comment]
Ok, so the behavior is right and the documentation is outdated/wrong in this case

**Comment by schubi2** [comment]
I have fixed the docu. Thank's!!!
