### ISSUE TITLE
Support hash characters in values

### ISSUE THREAD

**Issue by dmach** [openSUSE/libeconf#199]
ini file
```
[section]
hash_in_value = this is not # a comment
```
gets loaded as `this is not`

It might be good to add an option to disable inline comments so we can read such values.
Such behavior is default in Python's configparser.

**Comment by schubi2** [comment]
So, the Python's configparser does not support comments in the same line, or can it be managed by an option too ?
Could you please give me a hint where I can find the parser ?

**Comment by dmach** [comment]
It's the 'configparser' module that is part of python's standard library: https://docs.python.org/3/library/configparser.html
It is controlled with `comment_prefixes=('#',';')` and `inline_comment_prefixes=(';',)`
There are some existing tests upstream: https://github.com/python/cpython/blob/main/Lib/test/test_configparser.py

**Comment by schubi2** [comment]
Should be available in the next release (0.7)
Please set:
econf_set_opt ("PYTHON_STYLE=1");
inline_comment_prefixes is not supported. Even the docu says:
"When in doubt, avoid setting inline_comment_prefixes. "
