### ISSUE TITLE
Document search path for econf_ReadConfig

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/libeconf#203]
In the manual page we document the parameters for econf_ReadConfig, but not how we will use them to create the path for the config files.

Please add an example for this, e.g. 
/etc/<project>/...

**Comment by schubi2** [comment]
The docu on https://opensuse.github.io/libeconf has been really old. Sorry for that. I have updated it:

https://opensuse.github.io/libeconf/libeconf_8h.html#a0ed2af8bb1d8f4563a9ac5c83a798881
