### ISSUE TITLE
`tst-setgetvalues1` fails on aarch64, ppc64le and s390x

### ISSUE THREAD

**Issue by ggardet** [openSUSE/libeconf#210]
`tst-setgetvalues1` fails on aarch64, ppc64le and s390x.
Problem started when updating from 0.6.3 to 0.7.1: https://build.opensuse.org/request/show/1179643

Log:
```
[   25s] 52/62 tst-setgetvalues1     FAIL            0.02s   exit status 1
[   25s] >>> MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 LD_LIBRARY_PATH=/home/abuild/rpmbuild/BUILD/libeconf-0.7.1/aarch64-suse-linux/ ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /home/abuild/rpmbuild/BUILD/libeconf-0.7.1/aarch64-suse-linux/tests/tst-setgetvalues1
[   25s] ――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
[   25s] stderr:
[   25s] ERROR: couldn't get type 'Float': Value cannot be converted
[   25s] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by ggardet** [comment]
This can be narrowed down to update between `0.7.0` and `0.7.1`

**Comment by ggardet** [comment]
@schubi2

**Comment by ggardet** [comment]
The problem is from
```
if (!check_Float (key_file, FLT_MIN)) retval=1;
```

**Comment by ggardet** [comment]
> The problem is from
> 
> ```
> if (!check_Float (key_file, FLT_MIN)) retval=1;
> ```

I cannot spot why yet, but `econf_err getFloatValueNum(econf_file key_file, size_t num, float *result)` function returns `ERANGE 34 Numerical result out of range` error when tested with `FLT_MIN` which is `0.000000`.

**Comment by ggardet** [comment]
I think the problem is `setFloatValueNum` defines a _truncated_ value, which is out of range for `getFloatValueNum` afterwards.
Not sure why all architectures are affected but x86_64, though.

**Comment by schubi2** [comment]
Yes, the testcase still reports that values set with setFloatValueNum are the same as the values gotten by getFloatValueNum. The error exists only with FLT_MIN. In that case errno will be set but the values are correct. 
I think that could be more a compiler problem for the other architectures. I have removed the errno check for that case meanwhile. Former libeconfs  versions have not had this check at all. New version 0.7.2
