### ISSUE TITLE
Fails to build on GNU Hurd (PATH_MAX)

### ISSUE THREAD

**Issue by andhe** [openSUSE/libeconf#220]
GNU Hurd does not have PATH_MAX.

It could probably be considered a cleanup or even improvement to avoid using it on Linux as well.

Picking an example:

lib/helpers.c has this:

```
char *get_absolute_path(const char *path, econf_err *error) {                   
   char *absolute_path;                                                          
   if(*path != '/') {                                                            
     char buffer[PATH_MAX];                                                      
     if(!realpath(path, buffer)) {                 
```

man 3 readpath several ways to deal with this and here's one:

```
If  resolved_path is specified as NULL, then realpath() uses malloc(3) to allocate a buffer of up to PATH_MAX bytes to hold the resolved path‐
       name, and returns a pointer to this buffer.  The caller should deallocate this buffer using free(3).
```

In several other places in the code, snprintf is used to print into an array of PATH_MAX size. The return value of snprintf is not checked. If the path is ever truncated, noone would know.

For build logs, click on "failed" at:
https://buildd.debian.org/status/package.php?p=libeconf

A quick and dirty solution would be to:
```
#ifndef PATH_MAX
#define PATH_MAX 4096
#endif
```

**Comment by schubi2** [comment]
fixed
