### ISSUE TITLE
Check for EOF broken

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/libeconf#60]
Must not cast to char before comparing to EOF:

https://github.com/openSUSE/libeconf/blob/6d3ce5ae9084b6f6efe3e273d538a82b8aa97a8c/src/getfilecontents.c#L67

**Comment by parlt91** [comment]
Now using `ch` as type `size_t` instead of `char`.

**Comment by Vogtinator** [comment]
> Now using `ch` as type `size_t` instead of `char`.

Why? getc returns an `int`.
