### ISSUE TITLE
Reading invalid files crashes

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/libeconf#61]
https://github.com/openSUSE/libeconf/blob/6d3ce5ae9084b6f6efe3e273d538a82b8aa97a8c/src/libeconf.c#L92

Other members are not initialized. Please use calloc or struct assignments.

**Comment by parlt91** [comment]
@Vogtinator: I initialized the other struct members. This should be fixed now?

**Comment by Vogtinator** [comment]
Should work, but note that manual initialization is error-prone.

**Comment by schubi2** [comment]
closing. thanks !
