### ISSUE TITLE
API does not allow providing default values for keys

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/libeconf#62]
Currently the getter functions do not accept an argument for the default value which should be returned if the key is not explicitly set. This makes use in applications cumbersome as the error value needs to be returned. It might be a better idea to return the error code as return value instead and store the result in a provided pointer.

**Comment by thkukuk** [comment]
For me, this are two different, completely independent things:
1. provide a default value
2. return the error code as return value and store the result in a provided pointer instead.

About 1: we can discuss thus and change the API.
About 2: I don't like that, makes it only more complicated to use, I don't see an advantage of it. Beside that other libraries do it as we currently.

**Comment by Vogtinator** [comment]
> About 2: I don't like that, makes it only more complicated to use, I don't see an advantage of it. Beside that other libraries do it as we currently.

IMO it makes it easier to use and less error prone. With the `warn_unused_result` attribute error checking can be forced.

Current:

```
econf_err err;
int i = econf_getIntValue(file, "Group", "Key", &err);
if(err == ECONF_NOKEY)
    i = 42;
else if(err != ECONF_SUCCESS)
  abort();
```

Just provide a default value:

```
econf_err err;
int i = econf_getIntValue(file, "Group", "Key", 42, &err);
if(is_err(err))
  abort();
```

Both:

```
int i;
if(is_err(econf_getIntValue(file, "Group", "Key", 42, &i))
  abort();
```

**Comment by thkukuk** [comment]
Ok, if you want to do error checking, this makes it easier. But your example shows another problem: what if I don't want a default? For char * it's easy, but int?

**Comment by Vogtinator** [comment]
> Ok, if you want to do error checking, this makes it easier. But your example shows another problem: what if I don't want a default? For char * it's easy, but int?

There's always a default, for `int` it's -1. This makes it more explicit than implicit, which is good.

**Comment by thkukuk** [comment]
And that's the problem: I don't want a default, I want to have the value if the key exists or no value if the key does not exist. There are enough examples of such code.
And if we return the default and additional the error "ECONF_NOKEY", this makes the whole think only much more complicated.

Currently I think we should change the interface with the error code, but not add a default value. Or we provide a pointer to the default value, which makes the code only even more complicated.

**Comment by Vogtinator** [comment]
> And if we return the default and additional the error "ECONF_NOKEY", this makes the whole think only much more complicated.

That's what it currently does though, with the default hardcoded to `-1`.

**Comment by thkukuk** [comment]
No, this it not what it is currently doing. Currently, if error as pointer is provided, it's set to ECONF_NOKEY and the return value is undefined (most likely -1 or a NULL pointer).
With a provided default, do we return ECONF_NOKEY as error and the provided default as result? Makes the calling code really complex. Or do we return no error and the provided default as result? Then I never know if the value is from the config or the default.

**Comment by Vogtinator** [comment]
> Or do we return no error and the provided default as result? Then I never know if the value is from the config or the default.

I don't think that ever matters. If it in some case does actually matter, a separate function could check  whether (or even where) the key is set.

**Comment by thkukuk** [comment]
And I think this really matters. And we should not add hundreds of functions which do something similar, with the dnf requests, we will see enough additional functions and API extensions.

**Comment by laenion** [comment]
Why not just allow using NULL as the default value if one doesn't want to set one explicitly?

**Comment by thkukuk** [comment]
This works for char *, for bool you could provide an invalid integer, but what about int?
Your you make it really complicated, as I already wrote: you always provide a pointer to the default. But then Fabian's code would look like:

int i, default_int = 42;
if(is_err(econf_getIntValue(file, "Group", "Key", &default_int, &i))
  abort();

Or:
int i;
if(is_err(econf_getIntValue(file, "Group", "Key", NULL, &i))
  abort();

Does this make it really easier? Or will most people only provide "NULL"?

**Comment by thkukuk** [comment]
Changing the econf_set*Value functions should be done in any case, as returning true/false and additional an error code is really a bad thing.

**Comment by Vogtinator** [comment]
> And I think this really matters.

Why?

**Comment by thkukuk** [comment]
Why should it not matter? Beside that I answered in the parts you did not quote, we don't wont hundred of interfaces we have to maintain and keep API stable and there is enough code in the world which tries with ugly hacks to workaround this deficit of some few libraries, while the majority luckily does not have this problem.

**Comment by thkukuk** [comment]
The changed API for returning the error makes the code in most places much more simpler and better readable, good.

**Comment by thkukuk** [comment]
We could add a trivial wrapper:

econf_err econf_getDoubleValue_def(Key_File *kf, const char *group, const char *key, double *result, double def) { 
if (!kf) return ECONF_ERROR; 
econf_err error = econf_getDoubleValue(kf, group, key, result); 
if (error == ECONF_NOKEY) *result = def; return error; }

**Comment by AdamMajer** [comment]
I guess this can be closed now since it was already implemented?

But why not return ECONF_SUCCESS with default value? I think returning ECONF_NOKEY on default value makes it more cumbersome to check for failures as 2 values return success. An application that cares about NOKEY should not be using *Def wrappers.

**Comment by schubi2** [comment]
Yes,  econf_get*ValueDef is implemented with the default values.
