### ISSUE TITLE
Mismatch of group entry handling between parser and interface

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/libeconf#77]
We accept as group entries:

[group1]
group2
[group3]

the parser handles "group2" as group, getGroups returns it as group, but econf_get*Value does not find it.
See tst-groups3

I think the parser should only accept [...] as groups, we should remove the brackets during parsing and the public interfaces only use the group name without brackets.

**Comment by schubi2** [comment]
Done with: https://github.com/openSUSE/libeconf/pull/164
