### ISSUE TITLE
econf_setOption function

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/libeconf#82]
We should add a new function to the API:

econf_err econf_setOption (econf_file *, enum option, void *);

This could be e.g.:
econf_setOption (file, ALLOW_USER_CONFIG, [true,false]);
econf_setOption (file, ADD_DIR, "/run/project");

(Some of this options could mean, that we have to re-read the configuration files, as the order of directories could change).

**Comment by schubi2** [comment]
>econf_setOption (file, ALLOW_USER_CONFIG, [true,false]);
Does this mean that files in /etc will be ignored and only vendor settings will be taken ?
>econf_setOption (file, ADD_DIR, "/run/project");
Which priority have files of these added directories regarding /usr/etc and /etc ?

**Comment by thkukuk** [comment]
That was also a brainstorming idea. Don't remember anymore the details...
But as we have still no use case for this...
