### ISSUE TITLE
Handling of multiple key assignments ("lists") for merging

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/libeconf#99]
For handling lists for merging, the behaviour should be like this (how systemd does it):

For each Group/Key, there is a list of values.

If there is a ```Key=``` ("reset Key") statement, the list of values is cleared.
If there is a ```Key=foo``` ("assign to Key") statement, the value `foo` is appended to the list.

The `getValue` API methods should always return the last value assigned to a key.
A new `getValues` API could then return all values assigned to the key.

This has the advantage that there is no difference in merging whether a key is a list or a single value, which is not known at that time.

**Comment by schubi2** [comment]
I think that could be done by set:
`econf_set_opt("JOIN_SAME_ENTRIES=1");`
While parsing file(s) entries with the same key will be joined to an array which can be get by
`econf_getExtValue`
See https://github.com/openSUSE/libeconf/blob/master/tests/tst-string-append.c

**Comment by Vogtinator** [comment]
> I think that could be done by set:
econf_set_opt("JOIN_SAME_ENTRIES=1");

Not sure whether that's a good interface. This is not thread safe and affects the entire process, i.e. if multiple libraries in the same process use libeconf, they'll break each other.

**Comment by schubi2** [comment]
Short answer: Yes, you are right ;-)
